AWSTemplateFormatVersion: 2010-09-09
Description: Top-level stack template that deploys all the application resources including nested stacks.
Resources:
  VPCStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: ./vpc.yaml
      Parameters:
        VPCName: CurrencyExchangeVPC

  RDSStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: ./rds.yaml
      Parameters:
        DBName: CurrencyExchangeDB
        DBUser: admin
        DBAllocatedStorage: "5"
        DBInstanceClass: db.t3.small
        EC2SecurityGroup: !GetAtt VPCStack.Outputs.EC2SecurityGroup
        MultiAZ: "false"
        EnableReadReplica: "true"
        
Outputs:
  NestedStackLambdaArn:
    Description: ARN of the Lambda function from nested stack
    Value: !GetAtt VPCStack.Outputs.LambdaArn