AWSTemplateFormatVersion: 2010-09-09
Description: Top-level stack template that deploys all the application resources including nested stacks.

Parameters:
  BanxicoApiToken:
    Description: Banxico API Token for Currency Exchange application
    Type: String
    NoEcho: true

  Namespace:
    Description: Namespace for the application, used for resource naming and tagging
    Type: String
    Default: ce-dev

Resources:

  VPCStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: ./ecs_cluster.yaml
      Parameters:
        Namespace: !Ref Namespace
        VPCName: !Sub '${Namespace}-VPC'

  RDSStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: ./rds.yaml
      Parameters:
        DBName: CurrencyExchangeDB
        DBUser: ceadmin
        DBAllocatedStorage: "5"
        DBInstanceClass: db.t3.small
        ECSSecurityGroup: !GetAtt VPCStack.Outputs.FargateContainerSecurityGroup
        MultiAZ: "false"
        EnableReadReplica: "false"

  ECRRepositoryStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: ./ecr.yaml

  ECSFrontendStack:
    Type: AWS::CloudFormation::Stack
    DependsOn: 
      - VPCStack
      - ECRRepositoryStack
    Properties:
      TemplateURL: ./ecs_service.yaml
      Parameters:
        Namespace: !Ref Namespace
        ServiceName: CE-Frontend
        ImageUrl: !Sub '${ECRRepositoryStack.Outputs.ECRRepositoryUri}:frontend-v0.1.4'
        ContainerPort: 80
        ContainerCpu: '256'
        ContainerMemory: '512'
        Path: '*'
        Priority: 10
        DesiredCount: 2 


  ECSBackendStack:
    Type: AWS::CloudFormation::Stack
    DependsOn: 
      - VPCStack
      - ECRRepositoryStack
      - RDSStack
    Properties:
      TemplateURL: ./ecs_service.yaml
      Parameters:
        Namespace: !Ref Namespace
        ServiceName: CE-Backend
        ImageUrl: !Sub '${ECRRepositoryStack.Outputs.ECRRepositoryUri}:backend-v0.1.0'
        ContainerPort: 3000
        ContainerCpu: '256'
        ContainerMemory: '512'
        PublicPath: '/api/(currencies|health|rates).*'
        PrivatePath: '/api.*'
        Priority: 1
        DesiredCount: 2
        BanxicoApiToken: !Ref BanxicoApiToken


  LambdaSyncStack:
    Type: AWS::CloudFormation::Stack
    DependsOn: 
      - ECSBackendStack
    Properties:
      TemplateURL: ./lambda_sync.yaml
      Parameters:
        Namespace: !Ref Namespace
        APIUrl: !Sub '${VPCStack.Outputs.ExternalUrl}'

# Custom resource to trigger initial invocation of the Lambda function upon stack creation
  InitInvoke:
    Type: AWS::CloudFormation::CustomResource
    DependsOn: LambdaSyncStack
    Version: "1.0"
    Properties:
      ServiceToken: !GetAtt LambdaSyncStack.Outputs.LambdaSyncFunctionArn