AWSTemplateFormatVersion: "2010-09-09"

Description: 'AWS CloudFormation Sample Template RDS_MySQL_With_Read_Replica: Sample template showing how to create a highly-available, RDS DBInstance with a read replica. **WARNING** This template creates an Amazon Relational Database Service database instance and Amazon CloudWatch alarms. You will be billed for the AWS resources used if you create a stack from this template.'

Metadata:
  License: Apache-2.0

Parameters:

  Namespace:
    Description: Namespace for the application, used for resource naming and tagging
    Type: String
    Default: ce-dev

  DBName:
    Description: The database name
    Type: String
    Default: CurrencyExchangeDB
    MinLength: "1"
    MaxLength: "64"
    AllowedPattern: '[a-zA-Z][a-zA-Z0-9]*'
    ConstraintDescription: must begin with a letter and contain only alphanumeric characters.

  DBUser:
    Description: The database admin account username
    Type: String
    NoEcho: "true"
    MinLength: "1"
    MaxLength: "16"
    AllowedPattern: '[a-zA-Z][a-zA-Z0-9]*'
    ConstraintDescription: must begin with a letter and contain only alphanumeric characters.

  DBAllocatedStorage:
    Description: The size of the database (Gb)
    Type: Number
    Default: "5"
    MinValue: "5"
    MaxValue: "1024"
    ConstraintDescription: must be between 5 and 1024Gb.

  DBInstanceClass:
    Description: The database instance type
    Type: String
    Default: db.t3.small
    ConstraintDescription: must select a valid database instance type.

  ECSSecurityGroup:
    Description: The ECS security group of the ECS tasks that need access to the database
    Type: String
    Default: Default
    AllowedPattern: '[a-zA-Z0-9\-]+'
    ConstraintDescription: must be a valid security group name.

  MultiAZ:
    Description: Multi-AZ master database
    Type: String
    AllowedValues:
      - "true"
      - "false"
    Default: "false"
    ConstraintDescription: must be true or false.

  EnableReadReplica:
    Description: Enable the ReadReplica
    Type: String
    AllowedValues:
      - "true"
      - "false"
    Default: "true"
    ConstraintDescription: must be true or false.

Conditions:

  EnableReadReplica: !Equals
    - !Ref EnableReadReplica
    - "true"

Resources:


  DBECSSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Open database for access
      VpcId: 
        Fn::ImportValue: !Sub '${Namespace}:VPCId'  

  DBECSSecurityGroupIngress:
    Type: AWS::EC2::SecurityGroupIngress
    Properties:
      GroupId: !Ref DBECSSecurityGroup
      IpProtocol: tcp
      FromPort: "3306"
      ToPort: "3306"
      SourceSecurityGroupId: !Ref ECSSecurityGroup

  DBCredential:
    Type: AWS::SecretsManager::Secret
    Properties:
      Name: !Sub '${AWS::StackName}-DBCredential'
      GenerateSecretString:
        PasswordLength: 16
        ExcludeCharacters: '"@/\'
        RequireEachIncludedType: true


  DBSubnetGroup:
    Type: AWS::RDS::DBSubnetGroup
    Properties:
      DBSubnetGroupDescription: Subnet group for RDS DBInstance
      DBSubnetGroupName: !Sub '${AWS::StackName}-DBSubnetGroup'
      SubnetIds:
        - Fn::ImportValue: !Sub '${Namespace}:PrivateSubnetOne'
        - Fn::ImportValue: !Sub '${Namespace}:PrivateSubnetTwo'



  MainDB:
    DeletionPolicy: Snapshot
    UpdateReplacePolicy: Snapshot
    Type: AWS::RDS::DBInstance
    DependsOn: DBCredential
    Properties:
      DBName: !Ref DBName
      AllocatedStorage: !Ref DBAllocatedStorage
      BackupRetentionPeriod: 7
      DBInstanceClass: !Ref DBInstanceClass
      Engine: MySQL
      MasterUsername: !Ref DBUser
      MasterUserPassword: !Sub '{{resolve:secretsmanager:${DBCredential}}}'
      MultiAZ: !Ref MultiAZ
      PubliclyAccessible: false
      StorageEncrypted: true
      DBSubnetGroupName: !Ref DBSubnetGroup
      Tags:
        - Key: Name
          Value: Master Database
      VPCSecurityGroups:
        - !GetAtt DBECSSecurityGroup.GroupId

  ReplicaDB:
    DeletionPolicy: Retain
    UpdateReplacePolicy: Retain
    Type: AWS::RDS::DBInstance
    Metadata:
      cfn-lint:
        config:
          ignore_checks:
            - I3013
    Properties:
      SourceDBInstanceIdentifier: !Ref MainDB
      PubliclyAccessible: false
      DBInstanceClass: !Ref DBInstanceClass
      Tags:
        - Key: Name
          Value: Read Replica Database
    Condition: EnableReadReplica

Outputs:

  DBEndpoint:
    Description: Endpoint address of the master database
    Value: !GetAtt MainDB.Endpoint.Address
    Export:
      Name: !Sub '${Namespace}:DBEndpoint'

  DBUsername:
    Description: The database admin account username
    Value: !Ref DBUser
    Export:
      Name: !Sub '${Namespace}:DBUsername'

  DBCredential:
    Description: Name of the secret containing the database credential
    Value: !Ref DBCredential
    Export: 
      Name: !Sub '${Namespace}:DBCredential'
      
  DBName:
    Description: The database name
    Value: !Ref DBName
    Export:
      Name: !Sub '${Namespace}:DBName'

  ConnectionString:
    Description: JDBC connection string for the master database
    Value: !Join
      - ""
      - - mysql://
        - !GetAtt MainDB.Endpoint.Address
        - ':'
        - !GetAtt MainDB.Endpoint.Port
        - /
        - !Ref DBName

  ReplicaConnectionString:
    Description: JDBC connection string for the replica database
    Value: !Join
      - ""
      - - mysql://
        - !GetAtt ReplicaDB.Endpoint.Address
        - ':'
        - !GetAtt ReplicaDB.Endpoint.Port
        - /
        - !Ref DBName
    Condition: EnableReadReplica