AWSTemplateFormatVersion: '2010-09-09'
Description: S3 bucket for CloudFormation templates storage

Resources:
  CloudFormationTemplatesBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub '${AWS::StackName}-cfn-templates-${AWS::AccountId}'

      VersioningConfiguration:
        Status: Enabled
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      Tags:
        - Key: Purpose
          Value: CloudFormation Templates
        - Key: ManagedBy
          Value: CloudFormation

Outputs:
  BucketName:
    Description: Name of the S3 bucket for CloudFormation templates
    Value: !Ref CloudFormationTemplatesBucket
    Export:
      Name: !Sub '${AWS::StackName}-BucketName'
  
  BucketArn:
    Description: ARN of the S3 bucket
    Value: !GetAtt CloudFormationTemplatesBucket.Arn
    Export:
      Name: !Sub '${AWS::StackName}-BucketArn'